version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - apt-get update
      - apt-get install libgdal-dev --no-install-recommends -y
      - pip install pipenv
      - pipenv install --skip-lock --dev
      - pipenv install pygdal=="`gdal-config --version`.*"
  build:
    commands:
      - echo Build started on `date`
      - pipenv run tests
  post_build:
    commands:
      - echo Build completed on `date`
