version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - apt-get update
      - apt-get install libgdal-dev --no-install-recommends -y
      - pip install pipenv
      - pipenv sync --dev
      - pip install gdal==2.4.2
  build:
    commands:
      - echo Build started on `date`
      - pipenv run tests
  post_build:
    commands:
      - echo Build completed on `date`
