version: 0.2

phases:
    commands:
      - apt-get update
      - pip3 install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - pytest -v --cov-report term-missing --cov=src --cov=scripts
  post_build:
    commands:
      - echo Build completed on `date`
