version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
    commands:
      - apt-get update
  build:
    commands:
      - echo Build started on `date`
      - pytest -v --cov-report term-missing --cov=src --cov=scripts
  post_build:
    commands:
      - echo Build completed on `date`
